apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-traefik-dynamic
data:
  dynamic.yaml: |
    http:
      routers:
        api:
          entryPoints:
            - web
          rule: PathPrefix(`/api`)
          priority: 10
          service: api
        frontend:
          entryPoints:
            - web
          rule: PathPrefix(`/`)
          priority: 1
          service: frontend

      services:
        api:
          loadBalancer:
            servers:
              - url: "http://api:3001"
        frontend:
          loadBalancer:
            servers:
              - url: "http://frontend:80"
