apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-traefik-dynamic
data:
  dynamic.yaml: |
    http:
      middlewares:
        https-redirect:
          redirectScheme:
            scheme: https
            permanent: true

      routers:
        api-domain:
          entryPoints:
            - websecure
          rule: Host(`mealplanner.markushartmann.dev`) && PathPrefix(`/api`)
          priority: 200
          service: api
          tls:
            certResolver: letsencrypt
        frontend-domain:
          entryPoints:
            - websecure
          rule: Host(`mealplanner.markushartmann.dev`) && PathPrefix(`/`)
          priority: 100
          service: frontend
          tls:
            certResolver: letsencrypt
        api-domain-http:
          entryPoints:
            - web
          rule: Host(`mealplanner.markushartmann.dev`) && PathPrefix(`/api`)
          priority: 200
          middlewares:
            - https-redirect
          service: api
        frontend-domain-http:
          entryPoints:
            - web
          rule: Host(`mealplanner.markushartmann.dev`) && PathPrefix(`/`)
          priority: 100
          middlewares:
            - https-redirect
          service: frontend
        api-lan:
          entryPoints:
            - web
          rule: PathPrefix(`/api`)
          priority: 10
          service: api
        frontend-lan:
          entryPoints:
            - web
          rule: PathPrefix(`/`)
          priority: 1
          service: frontend

      services:
        api:
          loadBalancer:
            servers:
              - url: "http://api:3001"
        frontend:
          loadBalancer:
            servers:
              - url: "http://frontend:80"
